---

- name: Verify vm_storage_labeling_request Variable Provided
  ansible.builtin.assert:
    that:
      - vm_storage_labeling_request | default("", true) | length > 0
    fail_msg: "'vm_storage_labeling_request' Variable Not Provided"
    quiet: true

- name: Verify Required Properties Provided
  ansible.builtin.assert:
    that:
      - vm_storage_labeling_request | selectattr('namespace', 'undefined') | list | length == 0
    fail_msg: "Required property 'namespace' in 'vm_storage_labeling_request' Variable Not Provided"
    quiet: true

- name: Verify Labels or Annotations Provided
  ansible.builtin.assert:
    that:
      - >-
        (vm_storage_labeling_item.labels | default({}, true) | length > 0) or
        (vm_storage_labeling_item.annotations | default({}, true) | length > 0)
    fail_msg: >-
      Either 'labels' or 'annotations' must be provided for
      namespace '{{ vm_storage_labeling_item.namespace }}'
    quiet: true
  loop: "{{ vm_storage_labeling_request }}"
  loop_control:
    loop_var: vm_storage_labeling_item
    label: "Namespace: {{ vm_storage_labeling_item.namespace }}"

- name: Process Storage Volume Labeling Request
  ansible.builtin.include_tasks:
    file: _process_request.yml
  loop: "{{ vm_storage_labeling_request }}"
  loop_control:
    loop_var: vm_storage_labeling_current_request
    label: "Namespace: {{ vm_storage_labeling_current_request.namespace }}"

...
