---

- name: "_collect_vmis | Query VirtualMachineInstances — {{ _vm_consumption_report_query.namespace | default('all-namespaces') }}"
  kubernetes.core.k8s_info:
    api_key: "{{ vm_consumption_report_openshift_api_key }}"
    host: "{{ vm_consumption_report_openshift_host }}"
    api_version: "{{ vm_consumption_report_kubevirt_api_version }}"
    kind: VirtualMachineInstance
    namespace: "{{ _vm_consumption_report_query.namespace | default(omit) }}"
    label_selectors: "{{ _vm_consumption_report_query.label_selectors | default(omit) }}"
    validate_certs: "{{ vm_consumption_report_openshift_verify_ssl }}"
  register: _vm_consumption_report_vmi_response

- name: _collect_vmis | Append VMIs to Collection
  ansible.builtin.set_fact:
    _vm_consumption_report_vmis: >-
      {{ _vm_consumption_report_vmis + _vm_consumption_report_vmi_response.resources }}
...
